### ISSUE TITLE
Sourcecode of 1D Pong

### ISSUE THREAD

**Issue by cascha42** [Critters/TWANG#3]
Hey, sorry for abusing the "Issues" function.
Is the Sourcecode for the 1D Pong (seen at 34c3) online? I really want to build my own.

Thank you for your work

Sascha

**Comment by Critters** [comment]
I searched my files and didn't find anything, I think it was a quick test that got overwritten

**Comment by cascha42** [comment]
Really Pity.
If you found it i would be really thankfull!
